name: Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan==2

      - name: Configure GCC
        run: conan install . --build=missing -pr .conan/profiles/gcc

      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Build
        run: cmake --build --preset conan-release

      - name: Test
        run: ctest --preset conan-release --output-on-failure

  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan==2

      - name: Install Clang
        run: sudo apt-get install -y clang-14

      - name: Configure Clang
        run: conan install . --build=missing -pr .conan/profiles/clang

      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Build
        run: cmake --build --preset conan-release

      - name: Test
        run: ctest --preset conan-release --output-on-failure

  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan==2

      - name: Configure MSVC
        run: conan profile detect --force

      - name: Configure
        run: conan install . --build=missing -s build_type=Release

      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Build
        run: cmake --build --preset conan-release

      - name: Test
        run: ctest --preset conan-release --output-on-failure