name: Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install "conan>=2,<3"

      - name: Configure Conan
        run: conan profile detect --force

      - name: Configure GCC
        run: conan install . --build=missing -pr .conan/profiles/gcc

      - name: Configure CMake
        run: cmake --preset conan-gcc-release

      - name: Build
        run: cmake --build --preset conan-gcc-release

      - name: Test
        run: ctest --preset conan-gcc-release --output-on-failure

  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install "conan>=2,<3"

      - name: Configure Conan
        run: conan profile detect --force

      - name: Install Clang
        run: sudo apt-get install -y clang-14

      - name: Configure Clang
        run: conan install . --build=missing -pr .conan/profiles/clang

      - name: Configure CMake
        run: cmake --preset conan-clang-release

      - name: Build
        run: cmake --build --preset conan-clang-release

      - name: Test
        run: ctest --preset conan-clang-release --output-on-failure

  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install "conan>=2,<3"

      - name: Configure
        run: conan install . --build=missing -pr .conan/profiles/msvc

      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Build
        run: cmake --build --preset conan-release

      - name: Test
        run: ctest --preset conan-release --output-on-failure