name: Package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install "conan>=2,<3"

      - name: Configure Conan
        run: conan profile detect

      - name: Create package (GCC)
        run: |
          conan install . --profile=.conan/profiles/gcc --build=missing
          cmake --preset conan-gcc-release -DCMAKE_INSTALL_PREFIX=install
          cmake --build --preset conan-gcc-release --target install

      - name: Archive Conan package
        run: tar czvf tc.tar.gz install/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tc
          path: tc.tar.gz

  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1  
        with:
          arch: x64

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install "conan>=2,<3"

      - name: Configure Conan
        run: conan profile detect

      - name: Create package (MSVC)
        run: |
          conan install . --profile=.conan/profiles/msvc --build=missing
          cmake --preset conan-release -DCMAKE_INSTALL_PREFIX=install
          cmake --build --preset conan-release --target install

      - name: Archive Conan package
        run: Compress-Archive -Path "install" -DestinationPath tc.zip
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tc-conan-package-windows
          path: tc-conan-package.zip